### PR TITLE
S3 file rendering

### PR DESCRIPTION
**Pull request by niya-shroff**
- modified mockData.json for the table
- created those 36 test files in S3 bucket
- called backend endpoint to retrieve those files

Bugs/Errors:

- [x] 1. .doc and .msg files cannot be rendered so the user is given an option to download immediately
- [x] 2. .txt, .pdf, .xlsm, .xlsx files cannot be rendered (library import issues) and the user is not given any option to download immediately
- [x] 3. .zip files (ones that are pre zipped in S3) are not rendered so the user is given an option to download immediately

Download-Zip Endpoint:
- this is a WIP for the frontend to zip (once checkboxes are implemented we can do this)
- endpoint itself does work though

### CODE REVIEW

**Comment by Jet-lagged** [comment]
when including the pdf import, code does not compile. To merge into main, it has to at least compile
fileType handling could also use a refactor with all the if-else's, contact me for a refactor 

what works:
- image renders 
- htm/html renders
- txt does actually work with the "FileReader" reader, it just needs `<pre> data <pre>` in html to format white-space correctly
- doc, msg, zip, or any unsupported file types do download

what doesn't work:
- pdf
- xlsx/xlsm

Please fix what doesn't work OR simply make them downloads before un-drafting the PR

**Comment by khanghugo** [comment]
Should the file processing be in backend instead? I see with the file fetcher you are drawing binary data instead of the final file then assembled at the end. What is the merit to this over just getting the file? To be honest, I don't understand much stuffs in the backend so I cannot say much here. But for the front end, it looks a bit more complicated than it should be. If there is any advantages to that over what we are doing then I guess we can go with it.

**Comment by niya-shroff** [comment]
it’s the way to transfer the file essentially from the endpoint so when
it’s called we get it from s3 and frontend yeah we can optimize fs
libraries and use the iframe code for pdfs def needs clean up but I just
wanted to get smth working at a starting point but I’ll explain everything
more in a lil thing

**Comment by niya-shroff** [comment]
The code has been refactored, updated, and cleaned up. Everything should work now with a few exceptions: 

- [ ] .DOCX vs .docx file type bug (see TODO Section One With Comments)
- [ ] .doc file rendering (see TODO Section Three With Comments)

I suggest merging with Main since 95% of the functionality is working and complete. The next step besides fixing the two exceptions would be to edit the endpoint URL on the frontend (see TODO Section Two With Comments) after we merge with Main to access the files within the  FCTS_data/Attachments folders.

**Comment by niya-shroff** [comment]
not needed anymore

**Pull request closed without merging**
